export const ROUTES = {
  LOGIN: '/login',
  CUSTOMERS: '/customers',
  PRODUCTS: '/products',
  HISTORY: '/history',
  HISTORY_ACTIONS: '/history/actions',
  HISTORY_LICENSE_MOVING: '/history/licenseMoving',
  EMPLOYEES: '/handbooks/employees',
  WORKING_DAYS: '/handbooks/workingDays',
  INTEGRATION_TYPES: '/handbooks/integrationTypes',
  RESTAURANT_TYPES: '/handbooks/restaurantTypes',
  HOTEL_TYPES: '/handbooks/hotelTypes',
  MENU_TYPES: '/handbooks/menuTypes',
  PRICE_SEGMENTS: '/handbooks/priceSegments',
  PRODUCT_GROUPS: '/handbooks/productGroups',
  CUSTOMER_GROUPS: '/handbooks/customerGroups',
  CUSTOMER_STATUS: '/handbooks/customerStatus',
  COUNTRIES: '/handbooks/countries',
  CITIES: '/handbooks/cities',
  DISTRICTS: '/handbooks/districts',
} as const;
