export const ROUTES = {
  LOGIN: '/login',
  CUSTOMERS: '/customers',
  PRODUCTS: '/products',
  HISTORY: '/history',
  HISTORY_ACTIONS: '/history/actions',
  HISTORY_LICENSE_MOVING: '/history/licenseMoving',
  EMPLOYEES: '/handbooks/employees',
  WORKING_DAYS: '/handbooks/workingDays',
  INTEGRATION_TYPES: '/handbooks/integrationTypes',
  PRODUCT_GROUPS: '/handbooks/productGroups',
  CUSTOMER_GROUPS: '/handbooks/customerGroups',
  CUSTOMER_STATUS: '/handbooks/customerStatus',
  LICENSE_TYPES: '/handbooks/licenseTypes',
  COUNTRIES: '/handbooks/countries',
  CITIES: '/handbooks/cities',
  DISTRICTS: '/handbooks/districts',
  CUSTOMER_TAGS: '/handbooks/customerTags',
  PRODUCT_TAGS: '/handbooks/productTags',
  VALIDATORS: '/handbooks/validators',
} as const;
